# Generated by Django 2.2.14 on 2020-12-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('publications', '0002_auto_20201205_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='tags',
            field=models.ManyToManyField(related_name='publications', to='tags.Tag'),
        ),
    ]
