# Generated by Django 2.2.14 on 2020-12-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_publication_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='publication',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='publications', to='tags.Tag'),
        ),
    ]
