# Generated by Django 2.2.14 on 2020-12-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_auto_20201206_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='tags',
            field=models.ManyToManyField(related_name='publications', to='tags.Tag'),
        ),
    ]
