# Generated by Django 2.2.14 on 2020-12-08 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0009_auto_20201206_1454'),
        ('comments', '0002_auto_20201207_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='publications',
        ),
        migrations.AddField(
            model_name='comment',
            name='publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='publications.Publication'),
        ),
    ]
